name: flutter_application_1
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^1.0.0 
  google_fonts: ^6.1.0
  go_router: ^15.1.2
  cupertino_icons: ^1.0.2
  get: ^4.7.2
  intl: ^0.20.2
  table_calendar: ^3.0.9 
  shamsi_date: ^1.1.0
  flutter_persian_calendar: ^0.0.3
  persian_calendar_widget: ^0.5.0
  jalali_table_calendar_plus: ^1.1.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
